//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: WaitSetData.cpp
//  Source: E:/2y2b_cmake/spliceForTool/spliceForTool/dds/dds_msg_types/idl/WaitSetData.idl
//  Generated: Fri Mar 20 14:26:33 2020
//  OpenSplice 6.9.181018OSOS
//  
//******************************************************************

#include "WaitSetData.h"




