//******************************************************************
// 
//  Generated by IDL to C++ Translator
//  
//  File name: WaitSetData.h
//  Source: E:/2y2b_cmake/spliceForTool/spliceForTool/dds/dds_msg_types/idl/WaitSetData.idl
//  Generated: Fri Mar 20 14:26:33 2020
//  OpenSplice 6.9.181018OSOS
//  
//******************************************************************
#ifndef _WAITSETDATA_H_
#define _WAITSETDATA_H_

#include "sacpp_mapping.h"
#include "examples_export.h"


namespace WaitSetData
{
   struct Msg;

   struct OS_EXAMPLE_API Msg
   {
         DDS::Long subjectId;
         DDS::String_mgr systemId;
         DDS::Double time;
         DDS::String_mgr from;
         DDS::String_mgr topicName;
         DDS::String_mgr content;
   };

   typedef DDS_DCPSStruct_var < Msg> Msg_var;
   typedef DDS_DCPSStruct_out < Msg> Msg_out;
}




#endif
